### ISSUE TITLE
code isn't your own, stop stealing code lmao

### ISSUE THREAD

**Issue by 11111122233334** [agam778/CoolBot#1]

**Comment by agam778** [comment]
Bruh
I saw from tutorials

**Comment by BeakerThe1st** [comment]
agreed, skidding code is bad for everyone.

we love to see that you are learning code agam but please do not copypaste and pass it off to be your own.

**Comment by 11111122233334** [comment]
you copied from tutorials xd

**Comment by agam778** [comment]
I neved said that it's purely coded by me?
